# Tugas Kecil 1 IF3270  
## Eksplorasi library Algoritme Pembelajaran pada Jupyter Notebook


Anggota Kelompok:
- 13520065 - Rayhan Kinan Muhannad
- 13520081 - Andhika Arta Aryanto


In [2906]:
from sklearn.datasets import load_breast_cancer
from sklearn.utils import Bunch
import pandas as pd

data: Bunch = load_breast_cancer()

# Konversi data ke dataframe
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = pd.Series(data.target)

# Print 5 data teratas
print(df.head())


   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0             

In [2907]:
#Print informasi lebih mengenai dataset
print(data.target_names)


['malignant' 'benign']


Setelah melakukan eksplorasi singkat pada dataset, terdapat beberapa hal yang perlu diperhatikan:

- Dataset yang digunakan memiliki 30 atribut, dimana 29 atribut merupakan atribut input dan 1 atribut merupakan atribut output (target). Seluruh atribut merupakan atribut numerik. 

Berarti, dalam konteks tugas kecil ini, 29 atribut input tersebut akan menjadi variabel prediktor dalam model machine learning untuk menentukan apakah suatu data termasuk data berkelas 0 (malignant) atau 1 (benign).

## 1. Membagi Dataset menjadi Data Training dan Data Testing

In [2908]:
#Membagi dataset menjadi 80% data training dan 20% data testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2)


## 2. Melakukan pembelajaran dengan algoritma berikut ini:

* Decision Tree Classifier (http://scikit-learn.org/stable/modules/tree.html)  
* Id3 Estimator (https://github.com/svaante/decision-tree-id3)  
* K-Means Clustering (https://scikit-learn.org/0.19/modules/generated/sklearn.cluster.KMeans.html  
* Logistic Regression (https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)  
* Neural Network (https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html)   
* Support Vector Classifier (https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC)  


### 2.1. Decision Tree Classifier 

In [2909]:
from sklearn.tree import DecisionTreeClassifier, export_text

# Membuat model Decision Tree
DecisitionTreeModel = DecisionTreeClassifier(criterion="gini")
DecisitionTreeModel.fit(X_train, y_train)

# Tampilkan model pohon hasil Decision Tree dengan method export_text
text_representation = export_text(DecisitionTreeModel, feature_names= list(data.feature_names))
print(text_representation)


|--- mean concave points <= 0.05
|   |--- worst area <= 968.25
|   |   |--- worst symmetry <= 0.16
|   |   |   |--- class: 0
|   |   |--- worst symmetry >  0.16
|   |   |   |--- worst area <= 766.45
|   |   |   |   |--- worst texture <= 33.35
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- worst texture >  33.35
|   |   |   |   |   |--- worst texture <= 33.56
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- worst texture >  33.56
|   |   |   |   |   |   |--- class: 1
|   |   |   |--- worst area >  766.45
|   |   |   |   |--- worst texture <= 29.18
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- worst texture >  29.18
|   |   |   |   |   |--- mean area <= 658.40
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- mean area >  658.40
|   |   |   |   |   |   |--- class: 1
|   |--- worst area >  968.25
|   |   |--- texture error <= 1.44
|   |   |   |--- class: 0
|   |   |--- texture error >  1.44
|   |   |   |--- class: 1
|--- mean concave points >  0

### 2.2. Id3 Estimator

In [2910]:
# import six
# import sys
# sys.modules['sklearn.externals.six'] = six

# Import library ID3
# from id3 import Id3Estimator

# Membuat model ID3
# ID3model = Id3Estimator()
# ID3model.fit(X_train, y_train)

### 2.3. K-Means Clustering

In [2911]:
from sklearn.cluster import KMeans
from sklearn.linear_model import LogisticRegression
import numpy as np

# Membuat model K-Means (Unsupervised Learning)
KMeansModel = KMeans(n_clusters=2, n_init="auto", init="k-means++", algorithm="lloyd")
KMeansModel.fit(X_train)

# Membuat model LogisticRegression untuk memberi label pada model K-Means (Supervised Learning)
train_cluster_labels: np.ndarray[np.int32] = KMeansModel.labels_

X_train_clustered = train_cluster_labels.reshape(-1, 1)

LabeledKMeansModel = LogisticRegression(C=50, max_iter=1000)
LabeledKMeansModel.fit(X_train_clustered, y_train)

LogisticRegression(C=50, max_iter=1000)

### 2.4. Logistic Regression

In [2912]:
from sklearn.linear_model import LogisticRegression

# Membuat model Logistic Regression
LogisticRegressionModel = LogisticRegression(C=100, max_iter=20000)
LogisticRegressionModel.fit(X_train, y_train)

LogisticRegression(C=100, max_iter=20000)

### 2.5. Neural Network

In [2913]:
from sklearn.neural_network import MLPClassifier

# Membuat model Neural Network
MLPModel = MLPClassifier(hidden_layer_sizes=(60, 90, 30), max_iter=10000)
MLPModel.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(60, 90, 30), max_iter=10000)

### 2.6. Support Vector Classifier

In [2914]:
from sklearn.svm import SVC

# Membuat model SVM
SVCModel = SVC(C=100, kernel="linear")
SVCModel.fit(X_train, y_train)

SVC(C=100, kernel='linear')

## 3. Simpan model hasil pembelajaran dengan pustaka pickle

In [2915]:
import pickle

### 3.1. Decision Tree Classifier

In [2916]:
with open("./bin/DecisionTreeModel.pickle", "wb") as f:
    pickle.dump(DecisitionTreeModel, f)

### 3.2. Id3 Estimator

In [2917]:
# TODO: Save model ke dalam file

### 3.3. K-Means Clustering

In [2918]:
with open("./bin/KMeansModel.pickle", "wb") as f:
    pickle.dump(KMeansModel, f)

with open("./bin/LabeledKMeansModel.pickle", "wb") as f:
    pickle.dump(LabeledKMeansModel, f)

### 3.4. Logistic Regression

In [2919]:
with open("./bin/LogisticRegressionModel.pickle", "wb") as f:
    pickle.dump(LogisticRegressionModel, f)

### 3.5. Neural Network

In [2920]:
with open("./bin/MLPModel.pickle", "wb") as f:
    pickle.dump(MLPModel, f)

### 3.6. Support Vector Classifier

In [2921]:
with open("./bin/SVCModel.pickle", "wb") as f:
    pickle.dump(SVCModel, f)

## 4. Melakukan proses prediction dengan load model dan mengevaluasi hasil prediksi dengan menggunakan metric: Accuracy, Precision, Recall, dan F1 serta menampilkan Confusion Matrix

In [2922]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

### 4.1. Decision Tree Classifier

In [2923]:
with open("./bin/DecisionTreeModel.pickle", "rb") as f:
    DecisitionTreeModel: DecisionTreeClassifier = pickle.load(f)

    y_pred = DecisitionTreeModel.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    conf = confusion_matrix(y_test, y_pred)

    print(f"Accuracy:   {accuracy}")
    print(f"Precision:  {precision}")
    print(f"Recall:     {recall}")
    print(f"F1:         {f1}")
    print(f"Confusion Matrix:\n{conf}")

Accuracy:   0.9298245614035088
Precision:  0.9342105263157895
Recall:     0.9594594594594594
F1:         0.9466666666666667
Confusion Matrix:
[[35  5]
 [ 3 71]]


### 4.2. Id3 Estimator

In [2924]:
# TODO: Load model dari file

### 4.3. K-Means Clustering

In [2925]:
with open("./bin/KMeansModel.pickle", "rb") as f:
    KMeansModel: KMeans = pickle.load(f)

    test_cluster_labels: np.ndarray[np.int32] = KMeansModel.predict(X_test)
    X_test_clustered = test_cluster_labels.reshape(-1, 1)

    with open("./bin/LabeledKMeansModel.pickle", "rb") as f:
        LabeledKMeansModel: LogisticRegression = pickle.load(f)

        y_pred = LabeledKMeansModel.predict(X_test_clustered)

        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        conf = confusion_matrix(y_test, y_pred)

        print(f"Accuracy:   {accuracy}")
        print(f"Precision:  {precision}")
        print(f"Recall:     {recall}")
        print(f"F1:         {f1}")
        print(f"Confusion Matrix:\n{conf}")

Accuracy:   0.8421052631578947
Precision:  0.8111111111111111
Recall:     0.9864864864864865
F1:         0.8902439024390244
Confusion Matrix:
[[23 17]
 [ 1 73]]


### 4.4. Logistic Regression

In [2926]:
with open("./bin/LogisticRegressionModel.pickle", "rb") as f:
    LogisticRegressionModel: LogisticRegression = pickle.load(f)

    y_pred = LogisticRegressionModel.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    conf = confusion_matrix(y_test, y_pred)

    print(f"Accuracy:   {accuracy}")
    print(f"Precision:  {precision}")
    print(f"Recall:     {recall}")
    print(f"F1:         {f1}")
    print(f"Confusion Matrix:\n{conf}")

Accuracy:   0.9473684210526315
Precision:  0.9594594594594594
Recall:     0.9594594594594594
F1:         0.9594594594594594
Confusion Matrix:
[[37  3]
 [ 3 71]]


### 4.5. Neural Network

In [2927]:
with open("./bin/MLPModel.pickle", "rb") as f:
    MLPModel: MLPClassifier = pickle.load(f)

    y_pred = MLPModel.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    conf = confusion_matrix(y_test, y_pred)

    print(f"Accuracy:   {accuracy}")
    print(f"Precision:  {precision}")
    print(f"Recall:     {recall}")
    print(f"F1:         {f1}")
    print(f"Confusion Matrix:\n{conf}")

Accuracy:   0.9298245614035088
Precision:  0.9125
Recall:     0.9864864864864865
F1:         0.948051948051948
Confusion Matrix:
[[33  7]
 [ 1 73]]


### 4.6. Support Vector Classifier

In [2928]:
with open("./bin/SVCModel.pickle", "rb") as f:
    SVCModel: SVC = pickle.load(f)

    y_pred = SVCModel.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    conf = confusion_matrix(y_test, y_pred)

    print(f"Accuracy:   {accuracy}")
    print(f"Precision:  {precision}")
    print(f"Recall:     {recall}")
    print(f"F1:         {f1}")
    print(f"Confusion Matrix:\n{conf}")

Accuracy:   0.9385964912280702
Precision:  0.9466666666666667
Recall:     0.9594594594594594
F1:         0.9530201342281879
Confusion Matrix:
[[36  4]
 [ 3 71]]


## 5. Analisis hasil metrik evaluasi yang sudah diperoleh untuk semua algoritma pembelajaran dalam bentuk perbandingan nilai dan penjelasan singkat mengenai hasil tersebut

Setelah seluruh algoritma pembelajaran diaplikasikan pada setiap model, didapatkan bahwa rata - rata model yang dihasilkan memiliki metrik Accuracy, Precision, Recall, dan F1 Score yang cukup baik (sebagian besar melebihi 80%). 