# Tugas Kecil 1 IF3270  
## Eksplorasi library Algoritme Pembelajaran pada Jupyter Notebook


Anggota Kelompok:
- 13520065 - Rayhan Kinan Muhannad
- 13520081 - Andhika Arta Aryanto


In [55]:
from sklearn.datasets import load_breast_cancer
from sklearn.utils import Bunch
import pandas as pd

data: Bunch = load_breast_cancer()

# Konversi data ke dataframe
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = pd.Series(data.target)

# Print 5 data teratas
print(df.head())


   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0             

In [56]:
# Print informasi mengenai dataset
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [57]:
# Print informasi mengenai target
print(data.target_names)


['malignant' 'benign']


Setelah melakukan eksplorasi singkat pada dataset, terdapat beberapa hal yang perlu diperhatikan:

- Dataset yang digunakan memiliki 30 atribut, dimana 29 atribut merupakan atribut input dan 1 atribut merupakan atribut output (target). Seluruh atribut merupakan atribut numerik. 

Berarti, dalam konteks tugas kecil ini, 29 atribut input tersebut akan menjadi variabel prediktor dalam model machine learning untuk menentukan apakah suatu data termasuk data berkelas 0 (malignant) atau 1 (benign).

## 1. Membagi Dataset menjadi Data Training dan Data Testing

In [58]:
#Membagi dataset menjadi 80% data training dan 20% data testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2)


## 2. Melakukan pembelajaran dengan algoritma berikut ini:

* Decision Tree Classifier (http://scikit-learn.org/stable/modules/tree.html)  
* Id3 Estimator (https://github.com/svaante/decision-tree-id3)  
* K-Means Clustering (https://scikit-learn.org/0.19/modules/generated/sklearn.cluster.KMeans.html  
* Logistic Regression (https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)  
* Neural Network (https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html)   
* Support Vector Classifier (https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC)  


### 2.1. Decision Tree Classifier 

In [59]:
from sklearn.tree import DecisionTreeClassifier, export_text

# Membuat model Decision Tree
DecisitionTreeModel = DecisionTreeClassifier(criterion="gini")
DecisitionTreeModel.fit(X_train, y_train)

# Tampilkan model pohon hasil Decision Tree dengan method export_text
text_representation = export_text(DecisitionTreeModel, feature_names= list(data.feature_names))
print(text_representation)


|--- mean concave points <= 0.05
|   |--- mean area <= 696.25
|   |   |--- worst area <= 893.65
|   |   |   |--- worst smoothness <= 0.18
|   |   |   |   |--- worst texture <= 33.35
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- worst texture >  33.35
|   |   |   |   |   |--- worst texture <= 33.56
|   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- worst texture >  33.56
|   |   |   |   |   |   |--- class: 1
|   |   |   |--- worst smoothness >  0.18
|   |   |   |   |--- worst concavity <= 0.27
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- worst concavity >  0.27
|   |   |   |   |   |--- class: 0
|   |   |--- worst area >  893.65
|   |   |   |--- worst fractal dimension <= 0.08
|   |   |   |   |--- class: 0
|   |   |   |--- worst fractal dimension >  0.08
|   |   |   |   |--- class: 1
|   |--- mean area >  696.25
|   |   |--- worst texture <= 19.33
|   |   |   |--- class: 1
|   |   |--- worst texture >  19.33
|   |   |   |--- compactness error <= 0.02
|   | 

### 2.2. Id3 Estimator

In [60]:
import six
import sys
sys.modules['sklearn.externals.six'] = six

#Import library ID3
from id3 import Id3Estimator

#Membuat model ID3
ID3model = Id3Estimator()
ID3model.fit(X_train, y_train)

Id3Estimator()

### 2.3. K-Means Clustering

In [61]:
from sklearn.cluster import KMeans
from sklearn.linear_model import LogisticRegression
import numpy as np

# Membuat model K-Means (Unsupervised Learning)
KMeansModel = KMeans(n_clusters=2, n_init="auto", init="k-means++", algorithm="lloyd")
KMeansModel.fit(X_train)

# Membuat model LogisticRegression untuk memberi label pada model K-Means (Supervised Learning)
train_cluster_labels: np.ndarray[np.int32] = KMeansModel.labels_
X_train_clustered = train_cluster_labels.reshape(-1, 1)

LabeledKMeansModel = LogisticRegression(C=50, max_iter=1000)
LabeledKMeansModel.fit(X_train_clustered, y_train)

LogisticRegression(C=50, max_iter=1000)

### 2.4. Logistic Regression

In [62]:
from sklearn.linear_model import LogisticRegression

# Membuat model Logistic Regression
LogisticRegressionModel = LogisticRegression(C=100, max_iter=20000)
LogisticRegressionModel.fit(X_train, y_train)

LogisticRegression(C=100, max_iter=20000)

### 2.5. Neural Network

In [63]:
from sklearn.neural_network import MLPClassifier

# Membuat model Neural Network
MLPModel = MLPClassifier(hidden_layer_sizes=(60, 90, 30), max_iter=10000)
MLPModel.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(60, 90, 30), max_iter=10000)

### 2.6. Support Vector Machine

In [64]:
from sklearn.svm import SVC

# Membuat model SVM
SVCModel = SVC(C=100, kernel="linear")
SVCModel.fit(X_train, y_train)

SVC(C=100, kernel='linear')

## 3. Simpan model hasil pembelajaran dengan pustaka pickle

In [65]:
import pickle

### 3.1. Decision Tree Classifier

In [66]:
with open("./bin/DecisionTreeModel.pickle", "wb") as f:
    pickle.dump(DecisitionTreeModel, f)

### 3.2. Id3 Estimator

In [67]:
with open ("./bin/ID3Model.pickle", "wb") as f:
    pickle.dump(ID3model, f)

### 3.3. K-Means Clustering

In [68]:
with open("./bin/KMeansModel.pickle", "wb") as f:
    pickle.dump(KMeansModel, f)

with open("./bin/LabeledKMeansModel.pickle", "wb") as f:
    pickle.dump(LabeledKMeansModel, f)

### 3.4. Logistic Regression

In [69]:
with open("./bin/LogisticRegressionModel.pickle", "wb") as f:
    pickle.dump(LogisticRegressionModel, f)

### 3.5. Neural Network

In [70]:
with open("./bin/MLPModel.pickle", "wb") as f:
    pickle.dump(MLPModel, f)

### 3.6. Support Vector Machine

In [71]:
with open("./bin/SVCModel.pickle", "wb") as f:
    pickle.dump(SVCModel, f)

## 4. Melakukan proses prediction dengan load model dan mengevaluasi hasil prediksi dengan menggunakan metric: Accuracy, Precision, Recall, dan F1 serta menampilkan Confusion Matrix

In [72]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

### 4.1. Decision Tree Classifier

In [73]:
with open("./bin/DecisionTreeModel.pickle", "rb") as f:
    DecisitionTreeModel: DecisionTreeClassifier = pickle.load(f)

    y_pred = DecisitionTreeModel.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    conf = confusion_matrix(y_test, y_pred)

    print(f"Accuracy:   {accuracy}")
    print(f"Precision:  {precision}")
    print(f"Recall:     {recall}")
    print(f"F1:         {f1}")
    print(f"Confusion Matrix:\n{conf}")

Accuracy:   0.9298245614035088
Precision:  0.9473684210526315
Recall:     0.9473684210526315
F1:         0.9473684210526315
Confusion Matrix:
[[34  4]
 [ 4 72]]


### 4.2. Id3 Estimator

In [74]:
with open("./bin/ID3Model.pickle", "rb") as f:
    ID3model: Id3Estimator = pickle.load(f)

    y_pred = ID3model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    conf = confusion_matrix(y_test, y_pred)

    print(f"Accuracy:   {accuracy}")
    print(f"Precision:  {precision}")
    print(f"Recall:     {recall}")
    print(f"F1:         {f1}")
    print(f"Confusion Matrix:\n{conf}")

Accuracy:   0.9122807017543859
Precision:  0.9583333333333334
Recall:     0.9078947368421053
F1:         0.9324324324324325
Confusion Matrix:
[[35  3]
 [ 7 69]]


### 4.3. K-Means Clustering

In [75]:
with open("./bin/KMeansModel.pickle", "rb") as f:
    KMeansModel: KMeans = pickle.load(f)

    test_cluster_labels: np.ndarray[np.int32] = KMeansModel.predict(X_test)
    X_test_clustered = test_cluster_labels.reshape(-1, 1)

    with open("./bin/LabeledKMeansModel.pickle", "rb") as f:
        LabeledKMeansModel: LogisticRegression = pickle.load(f)

        y_pred = LabeledKMeansModel.predict(X_test_clustered)

        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        conf = confusion_matrix(y_test, y_pred)

        print(f"Accuracy:   {accuracy}")
        print(f"Precision:  {precision}")
        print(f"Recall:     {recall}")
        print(f"F1:         {f1}")
        print(f"Confusion Matrix:\n{conf}")

Accuracy:   0.8508771929824561
Precision:  0.8172043010752689
Recall:     1.0
F1:         0.8994082840236686
Confusion Matrix:
[[21 17]
 [ 0 76]]


### 4.4. Logistic Regression

In [76]:
with open("./bin/LogisticRegressionModel.pickle", "rb") as f:
    LogisticRegressionModel: LogisticRegression = pickle.load(f)

    y_pred = LogisticRegressionModel.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    conf = confusion_matrix(y_test, y_pred)

    print(f"Accuracy:   {accuracy}")
    print(f"Precision:  {precision}")
    print(f"Recall:     {recall}")
    print(f"F1:         {f1}")
    print(f"Confusion Matrix:\n{conf}")

Accuracy:   0.9736842105263158
Precision:  0.974025974025974
Recall:     0.9868421052631579
F1:         0.9803921568627451
Confusion Matrix:
[[36  2]
 [ 1 75]]


### 4.5. Neural Network

In [77]:
with open("./bin/MLPModel.pickle", "rb") as f:
    MLPModel: MLPClassifier = pickle.load(f)

    y_pred = MLPModel.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    conf = confusion_matrix(y_test, y_pred)

    print(f"Accuracy:   {accuracy}")
    print(f"Precision:  {precision}")
    print(f"Recall:     {recall}")
    print(f"F1:         {f1}")
    print(f"Confusion Matrix:\n{conf}")

Accuracy:   0.956140350877193
Precision:  0.9733333333333334
Recall:     0.9605263157894737
F1:         0.9668874172185431
Confusion Matrix:
[[36  2]
 [ 3 73]]


### 4.6. Support Vector Machine

In [78]:
with open("./bin/SVCModel.pickle", "rb") as f:
    SVCModel: SVC = pickle.load(f)

    y_pred = SVCModel.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    conf = confusion_matrix(y_test, y_pred)

    print(f"Accuracy:   {accuracy}")
    print(f"Precision:  {precision}")
    print(f"Recall:     {recall}")
    print(f"F1:         {f1}")
    print(f"Confusion Matrix:\n{conf}")

Accuracy:   0.9824561403508771
Precision:  0.9868421052631579
Recall:     0.9868421052631579
F1:         0.9868421052631579
Confusion Matrix:
[[37  1]
 [ 1 75]]


## 5. Analisis hasil metrik evaluasi yang sudah diperoleh untuk semua algoritma pembelajaran dalam bentuk perbandingan nilai dan penjelasan singkat mengenai hasil tersebut

Setelah seluruh algoritma diaplikasikan pada setiap model pembelajaran, didapatkan bahwa rata - rata model yang dihasilkan memiliki metrik Accuracy, Precision, Recall, dan F1 Score yang cukup baik (sebagian besar melebihi 80%). Jika seluruh model pembelajaran tersebut diurutkan berdasarkan parametrik Accuracy dan F1 Score, maka model yang terbaik adalah Logistic Regression. Terdapat beberapa hal yang menyebabkan Logistic Regression cocok untuk memodel permasalahan tersebut. Model Logistic Regression umumnya digunakan untuk menangani data dengan kelas target bertipe binary (boolean). Dataset breast cancer memiliki kelas target yang bersifat binary, yaitu benign (jinak) atau malign (ganas). Selain itu, model Logistic Regression dapat bekerja dengan baik dalam menangani parameter dengan tipe data desimal (float) seperti pada permasalahan di atas.

Tidak hanya model Logistic Regression, model Support Vector Machine (SVM) juga cukup akurat dalam memodelkan permasalahan breast cancer. Model SVM cocok digunakan untuk menangani berbagai permasalahan dengan jumlah parameter yang banyak (data berdimensi tinggi). Kernel SVM yang cocok digunakan untuk memodelkan permasalahan ini adalah linear kernel. Hal tersebut dikarenakan linear kernel dapat memodelkan kelas target bertipe binary secara akurat dengan mencari linear boundary (optimal hyperplane) yang memisahkan kedua kelas tersebut. Linear kernel juga cocok digunakan pada model ini dikarenakan linear kernel cenderung tidak mengalami overfitting ketika diaplikasikan pada dataset yang kecil.

Model Decision Tree memiliki tingkat Accuracy dan F1 Score yang tidak jauh berbeda dengan model SVM. Hal ini dikarenakan umumnya kedua model melakukan klasifikasi berdasarkan pembuatan linear boundary yang paling optimum. Model Decision Tree bekerja dengan mencari suatu linear boundary diantara seluruh kelas dataset yang dapat memberikan maksimum Information Gain dengan perhitungan Entropy. Model Decision Tree umumnya dapat memodelkan hubungan statistik antar kelas pada dataset secara akurat. Hal tersebut dikarenakan model Decision Tree dapat juga ditranslasikan sebagai kumpulan logical rules yang dapat menggambarkan hubungan tersebut. Pada persoalan breast cancer, atribut yang terdapat di dalam tidak sepenuhnya independen antara satu sama lain, sehingga pembentukkan pohon keputusan akan memiliki simpul yang sedikit dan mudah untuk dipartisi.

ID3 juga memiliki tingkat Accuracy dan F1 Score yang tidak jauh berbeda dengan model Decision Tree, bahkan terkadang lebih baik. Hal ini dikarenakan kedua model memiliki cara kerja yang hampir sama. Model ID3 bekerja dengan mencari suatu linear boundary diantara seluruh kelas dataset yang dapat memberikan maksimum Information Gain dengan perhitungan Entropy. Model ID3 umumnya dapat memodelkan hubungan statistik antar kelas pada dataset secara akurat. Hal tersebut dikarenakan model ID3 dapat juga ditranslasikan sebagai kumpulan logical rules yang dapat menggambarkan hubungan tersebut. Pada persoalan breast cancer, atribut yang terdapat di dalam tidak sepenuhnya independen antara satu sama lain, sehingga pembentukkan pohon keputusan akan memiliki simpul yang sedikit dan mudah untuk dipartisi.

Setelah model ID3, model yang tidak kalah akurat untuk diaplikasikan pada permasalahan breast cancer dataset adalah Multilayer Perceptron (subbagian Neural Network). Model Multilayer Perceptron dapat digunakan untuk memodelkan berbagai macam permasalahan, seperti Computer Vision, Natural Language Processing, Search Engine, dan permasalahan lainnya. Hal ini dikarenakan Multilayer Perceptron cenderung bersifat versatile dan mudah beradaptasi jika dibandingkan model pembelajaran lainnya. Namun untuk beberapa permasalahan khusus, model Multilayer Perceptron dapat diungguli oleh model pembelajaran lainnya, seperti pada permasalahan breast cancer disini. Selain itu, model Multilayer Perceptron umumnya membutuhkan perhitungan komputasi yang lebih banyak dari model pembelajaran lainnya dikarenakan adanya proses backpropagation hingga mencapai keadaan konvergen.

Terakhir, model yang memiliki tingkat Accuracy dan F1 Score paling rendah adalah model K-Means Clustering yang diberi label oleh bantuan model Logistic Regression. Model K-Means Clustering merupakan algoritma unsupervised learning, sehingga model tersebut tidak dapat memberikan label akurat pada prediksi yang dilakukannya. Oleh karena itu, diperlukan model Logistic Regression yang memetakan label individu hasil perhitungan K-Means Clustering ke dalam kelas target. Perhitungan klasifikasi yang dilakukan oleh model Logistic Regression pada permasalahan ini tidak akan memiliki dampak yang signifikan terhadap perhitungan yang dilakukan oleh K-Means Clustering. Oleh karena itu, nilai Accuracy dan F1 Score yang didapatkan pada perhitungan di atas hampir seluruhnya disebabkan oleh model K-Means Clustering. K-Means Clustering umumnya digunakan untuk mencari kemiripan antara setiap instance dengan instance lainnya, lalu mengelompokkan instance tersebut ke dalam salah satu kategori. Pada umumnya, model K-Means Clustering tidak dapat memodelkan suatu dataset dengan jumlah atribut yang banyak, seperti pada persoalan breast cancer dataset di atas. Selain itu, model K-Means Clustering menanggap seluruh cluster yang terbentuk pada dataset memiliki varians yang sama (mungkin saja berbeda untuk beberapa dataset)

## 6. Lakukan k-fold cross validation (dengan k=10), dengan fungsi cross_validate pada algoritme DecisionTreeClassifier saja untuk dataset breast cancer. Tampilkan hasil akurasi dan F1 score dari 10-fold cross validation. Bandingkan dan analisis hasil pembandingan dengan akurasi dan F1 score DecisionTreeClassifier pada hasil di butir (4)

In [79]:
from sklearn.model_selection import cross_validate

X = data.data
y = data.target
scores = cross_validate(DecisitionTreeModel, X, y, cv=10, scoring=["accuracy","f1"])

print(f"Accuracy: {scores['test_accuracy'].mean()}")
print(f"F1:       {scores['test_f1'].mean()}")


Accuracy: 0.9156954887218044
F1:       0.9333038122215825


Bila dibandingkan dengan hasil perhitungan dari akurasi dan F1 score DecisionTreeClassifier , terlihat bahwa hasil evaluasi model menggunakan teknik K-Fold Cross Validation tidak menunjukkan perbedaan yang signifikan dengan model biasa. Hal ini menunjukkan bahwa model yang digunakan sebelumnya sudah cukup baik.

Biasanya, penggunaan teknik K-Fold digunakan untuk memperbaiki model dengan akurasi yang rendah misal karena overfitting. Namun, pada kasus ini, model Decision Tree Classifier yang digunakan memiliki akurasi yang cukup baik, sehingga tidak perlu dilakukan perbaikan dengan teknik K-Fold Cross Validation.


